[package]
name = "rquickjs-serde"
version = "0.1.0"
edition = "2024"

[dependencies]
rquickjs = "0.9"
serde = "1"

[dev-dependencies]
quickcheck = "1"
serde = { version = "1", features = ["derive"] }
